### ISSUE TITLE
Add a italian translation

### ISSUE THREAD

**Issue by blaues0cke** [blaues0cke/PiSleepTalk#169]
You can find the localisation files in `PiSleepTalk/frontend/locales/`.

**Comment by RadValentin** [comment]
I'd like to give this a go

**Comment by blaues0cke** [comment]
Nice, thank you!

**Comment by blaues0cke** [comment]
@RadValentin Can you please open a pull request? Thanks!

**Comment by RadValentin** [comment]
@blaues0cke Hey, sure thing, need to do some cleanup beforehand. I'll submit a PR tomorrow night.

**Comment by blaues0cke** [comment]
Alright, no problem. Just wanted to prevent that you just forgot it! :-)
