### ISSUE TITLE
Add support for a hardware switch to enable and disable recording mode

### ISSUE THREAD

**Issue by blaues0cke** [blaues0cke/PiSleepTalk#47]

**Comment by ottojo** [comment]
http://wiringpi.com/the-gpio-utility/

**Comment by ottojo** [comment]
Install WiringPI
http://wiringpi.com/download-and-install/

on startup:

```
gpio mode 0 in
gpio mode 0 up
```

wait until switch closed:

```
gpio wfi 0 falling
```

wait until switch opened:

```
gpio wfi 0 rising
```

Switch wired up between GPIO0 (Raspberry pin 11, http://wiringpi.com/pins/)

**Comment by blaues0cke** [comment]
Sexy, will check this right after #21
